### ISSUE TITLE
index preface

### ISSUE THREAD

**Issue by tampakis** [pulibrary/cicognara-rails#110]
and incorporate into catalogo display

**Comment by jpstroop** [comment]
This has some UI implications. Could probably use the same static page approach.

**Comment by tpendragon** [comment]
Display Preface in the "Browse" listing of the catalogo.

**Comment by tpendragon** [comment]
This should be in Figgy somewhere, @escowles needs to find it.

**Comment by escowles** [comment]
This is the Figgy object: https://figgy.princeton.edu/catalog/53b62d3a-8482-4547-9dca-1cf060f52284

**Comment by cwulfman** [comment]
See [https://github.com/pulibrary/cicognara-rails/pull/359 ](https://github.com/pulibrary/cicognara-rails/pull/359). NB this only affects the partials; I've done nothing with the solr index.
