### ISSUE TITLE
Changes to MARC record display

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#116]
Here's a stab at changes:
- [ ] Remove `533`
- [ ] Remove the string `[microform` from anywhere in the `245`
- [ ] `710`s with a subfield `a` that starts with "Fondo Cicognara" or "Leopoldo Cicognara Program" should be completely removed (whole `710`, not just `a`.

This would be a good start anyway.

**Comment by jpstroop** [comment]
Two separate issues here:
 * There are some fields that shouldn't display or need to be altered in the record view
 * There is a use case for being able to download a set of MARC records that represent the resources in cicognara.org. Again fields may need to be stripped or added.

**Comment by jpstroop** [comment]
Download of records is in a separate issue, #134

**Comment by cwulfman** [comment]
I don't know why this didn't get closed with the PR; I'm closing it manually now.
