### ISSUE TITLE
Need a "news" page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#117]
@axamei maybe do w/ "about" page?

**Comment by jpstroop** [comment]
@axamei I had a conversation with Sandy, and follow up with the partners today. This (from my slide deck) is basically what they're expecting in terms of pages:

![cicognara org partners september 2016](https://cloud.githubusercontent.com/assets/999701/18521734/565400cc-7a7b-11e6-9638-1234ba82c0d6.png)

cf. #112 #111

**Comment by axamei** [comment]
@jpstroop Looks good. We'll set it up so they have all the pages they want.
