### ISSUE TITLE
Add browse button to header?

### ISSUE THREAD

**Issue by axamei** [pulibrary/cicognara-rails#123]
Do we want to add "Browse the Catalogo" next to search box on all pages?

<img width="1440" alt="browse_catalogo" src="https://cloud.githubusercontent.com/assets/8161144/18792732/a3e081ce-8185-11e6-8964-d0591375f862.png">

**Comment by jpstroop** [comment]
Let's try it. I think it could get confusing, but I can't think of a better alternative.
