### ISSUE TITLE
Section 2.13 item partials are not being generated

### ISSUE THREAD

**Issue by axamei** [pulibrary/cicognara-rails#124]
Items above 4155 (in section 2.13) do not have item partials breaking the pagination.

http://libruby-dev.princeton.edu/cicognara/catalog/4321

**Comment by tampakis** [comment]
@cwulfman can you take a look at this? Section 2.13 is the last section of the catalogo and while the section partial gets generated for the "browse" view from the xsl, the individual item partials aren't.

**Comment by cwulfman** [comment]
Should be fixed now; see PR.

**Comment by tampakis** [comment]
Works great, thanks @cwulfman!
