### ISSUE TITLE
Migrate pudl0134 into Plum

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#130]
These are locally digitized Cicognara volumes

**Comment by jpstroop** [comment]
@tpendragon @escowles this could happen any time we're ready (doesn't have to wait for the sprint)

**Comment by tpendragon** [comment]
Assuming 66 is the right count, I think this is done: http://lib-plum1.princeton.edu/catalog?f%5Bmember_of_collections_ssim%5D%5B%5D=Bibliotheca+Cicognara&q=

**Comment by escowles** [comment]
I see 43 items in http://pudl.princeton.edu/collections/pudl0134 — so I assume there were uningested items on disk that were ingested into Plum, beyond what was in PUDL.

**Comment by jpstroop** [comment]
Faster than months! Keep this open if you want and I'll check later in the
week.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
