### ISSUE TITLE
Rake task to ingest add partner manifests from spreadsheets

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#131]
Could do after #130, using our data from Plum.

**Comment by jpstroop** [comment]
Here's the template:
https://docs.google.com/spreadsheets/d/1vxBfFK1fb9UKxwzZnIAHfCuagBaQGx1CNoBYJmkhZe8/edit#gid=0

I think only `digital_cico_number`, `manifest`, and `contributing_library` should be required. Can't remember if we have a model for contributing library or not.

**Comment by jpstroop** [comment]
Task should check for an existing `owner_system_number` and replace that record if it is found. This is the mechanism partners have for replacing/updating their holdings in bulk,

**Comment by jpstroop** [comment]
Rights should be a URI (see #59)

**Comment by jpstroop** [comment]
`manifest` should be a URI

**Comment by jpstroop** [comment]
`based_on_original` could probably default to false, but that might just get confusing.

**Comment by escowles** [comment]
Are the requirements for manifest, rights, owner_system_number, and based_on_original specific to the CSV import? Or should we just add them as validations on the model?

**Comment by escowles** [comment]
I went with model validations for https://github.com/pulibrary/cicognara-rails/pull/163 — so there's a ton of test updates to make the test objects have all the required fields, etc.
