### ISSUE TITLE
Filter by whether or not a digitized version is available or not

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#135]

**Comment by escowles** [comment]
Useful for finding what is loaded already while we are loading the microfiche scans — remove after those are all loaded?

**Comment by jpstroop** [comment]
I think the may be some volumes that aren't with the fiche, so it may go a little past that. And, now that I think about it,  the partners may not want the fiche to count.

**Comment by tpendragon** [comment]
That last point seems important. The fiche is just a version now, yeah? Can we close this issue with "if any version with a manifest exists, have it count in the facet" and then adjust later if we need to?

**Comment by jpstroop** [comment]
Let's keep it simple until we hear otherwise. If `based_on_original?` is true, then it should come up.
