### ISSUE TITLE
Move site to cicognara.org

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#138]
This has to happen by 11/1. Work w/ @gpmenos to get a VM and transfer the domain.

**Comment by kevinreiss** [comment]
The domain is currently attached to the github hosted site at this repo https://github.com/cicognara/cicognara.github.io.

**Comment by jpstroop** [comment]
It's a relatively small app, so I think we should try to keep everything (Solr, DB, Rails) on one box. Sending an email now.

**Comment by jpstroop** [comment]
> Phil,
>
> We're going to need a VM for the cicognara.org application sometime soon. That domain currently points to https://github.com/cicognara/cicognara.github.io, but we need to switch it over to our Rails application by 11/1; Trey and Esmé will be working on the application during the week of 10/24, so it would be nice if they could have the VM by then.
>
> As this is a relatively small and self-contained application, I'd like us to try to fit all of the dependencies (NGINX/Passenger/Rails, Solr, PSQL) onto one machine, which I think would require (I'm guessing) 20GB RAM, 60 GB of storage, and four cores. I know that's a little large, but I think it makes sense if we can manage it. Probably easiest to not worry about Puppet for this one.
>
> We'll also need an SSL cert (maybe two; see next para).
>
> Because there's already a site at cicognara.org and we'd like to limit its downtime, I propose we do this in two phases:
>
> 1. Set up the machine and alias it as cicognara.princeton.edu
> 2. After the app is deployed there, update the cicognara.org domain to point at that machine.
> 
> Make sense?
>
> Thanks,
> 
> Jon

**Comment by jpstroop** [comment]
TODO:
 * [ ] cicognara.org
 * [ ] SSL cert
