### ISSUE TITLE
Style forms

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#139]
Can't get to the forms right now, so this is just a placeholder--seem to remember that they needed some CSS :heart:

**Comment by axamei** [comment]
When this happens, add some padding to the select options in the search box. Looks weird in Chrome: 
<img width="410" alt="cico-search" src="https://cloud.githubusercontent.com/assets/8161144/19867697/339510d8-9f7b-11e6-93bb-0c0ac8739351.png">
