### ISSUE TITLE
clarify meaning of "based on original"

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-rails#146]
Does the checkbox mean "digitized from the fiche," or does it mean some measure of similarity to the item in the Vatican?

**Comment by tpendragon** [comment]
Does this mean "this version was the fiche scan"

**Comment by jpstroop** [comment]
Usually, yes. But at some point we may get scans from the Vatican as well.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
