### ISSUE TITLE
User and Admin roles

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#17]

**Comment by jpstroop** [comment]
And maybe a SuperAdmin who can elevate users?

**Comment by escowles** [comment]
* Users can CRUD version records (any? or scoped to institution?)
* Admin users can promote users to Admin

**Comment by escowles** [comment]
If we're going to use OAuth, we probably need 3 levels of user:

1. User (anyone with OAuth credentials)
2. Curator (promoted from User), can CRUD versions
3. Admin (promoted from Curator), can promote users

**Comment by jpstroop** [comment]
That sounds right to me, though I wonder what plain old Users get? Bookmarks, I guess?

**Comment by escowles** [comment]
Yes, they'd get the basic Blacklight bookmarks, saved searches, etc.  When the site is live, it'll be appropriate for end users.
