### ISSUE TITLE
favicon should not be blacklight

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#172]

**Comment by eliotjordan** [comment]
Just use the pulibrary favicon right? You know, I don't even notice them anymore. Chrome and Firefox don't show them in the address bar anymore.

**Comment by jpstroop** [comment]
I think because its cicognara we might want something different. I still see them in the Chrome tabs:

![image](https://cloud.githubusercontent.com/assets/999701/19819296/f8c872e8-9d21-11e6-8037-eae0b40014ba.png)

**Comment by cwulfman** [comment]
Maybe just a C in Axa's font? (Maybe a screenshot from Cicognara.org?)

**Comment by jpstroop** [comment]
Maybe helpful? https://github.com/pulibrary/cicognara-rails/blob/master/app/assets/images/cicognara-logo.svg
