### ISSUE TITLE
Get rid of Welcome text

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#173]
http://cicognara.org/catalog

Welcome, Here’s how to get started, etc.

Propose that after we have sort by Catalogo Nr (#170) , we redirect /catalog (with no params) to http://cicognara.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q= sorted by cico number. Is that possible?

**Comment by tpendragon** [comment]
Yeah, I don't think we even have to redirect, can just disable that front page.

How'd you even get there? Just put in the path?

**Comment by jpstroop** [comment]
Empty search

**Comment by jpstroop** [comment]
But without that params there would just be empty space I think. Need to run a query.
