### ISSUE TITLE
Hide Browse the Catalogo button at http://cicognara.org/catalogo

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#175]
Doesn't really make sense there

**Comment by tpendragon** [comment]
You sure? I like that the banner is consistent.

**Comment by jpstroop** [comment]
I just don't like clicking on a button that doesn't take me anywhere.

**Comment by axamei** [comment]
I think we should keep it there for consistency. 

Links to other pages don't disappear when user is viewing said page, e.g., "News" link still appears in header when user views news page... It would feel awkward to see it missing.

**Comment by jpstroop** [comment]
:+1:
