### ISSUE TITLE
PUL logo too large

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#187]
@axamei - I tried switching out the PUL logo in the footer for one of the transparent PNGs that we have [here](https://github.com/pulibrary/pul_graphics/tree/master/pul/png). Unfortunately the one that has our name and logo is way too big; we need something closer to square. Any chance we could make one that has the logo above and text underneath?

**Comment by jpstroop** [comment]
I guess we could also go with just the logo and no text; not sure hoe anyone feels about that.

**Comment by escowles** [comment]
+1 to the logo with no text — Heidelberg is the only other logo with text, so it would fit in much better.

**Comment by axamei** [comment]
Logo only works for me. We can add title attributes to each image so the names of the institutions pop up when you mouseover them.

**Comment by jpstroop** [comment]
@axamei do you want to take care of this, or shall one of us?
