### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#191]

**Comment by jpstroop** [comment]
I just did this and it seems to be working. Can someone else test and close if so?

**Comment by escowles** [comment]
I just tried http://cicognara.org and http://cicognara.princeton.edu and both served me over HTTP.

**Comment by jpstroop** [comment]
Cache?

**Comment by jpstroop** [comment]
cicognara.princeton.edu isn't working for me either, but cicognara.org is.

**Comment by jpstroop** [comment]
is there somewhere else to make a change besides `default`?

**Comment by escowles** [comment]
`curl -i --max-redirs 0 http://cicognara.org/` returns content instead of redirecting

**Comment by escowles** [comment]
It should be `/etc/nginx/sites-available/default` — I don't see any redirection config there — I still see the passenger config.

**Comment by jpstroop** [comment]
Do in the Rails app until Phil can get Puppet updated.
