### ISSUE TITLE
Document Cicognara identifiers

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#22]

**Comment by escowles** [comment]
See https://docs.google.com/drawings/d/1_2eLrAScu4RjpUg8RvKw8XMP9pi0HrdTH_pa3Jtx52s/edit

**Comment by jpstroop** [comment]
Make a diagram and link it into the README

**Comment by escowles** [comment]
Does the diagram wind up being a subset of the ER diagram — Basically, the Entity-Book-Version part, with the identifiers called out?

https://docs.google.com/drawings/d/1MLnL8JpUS84DX7fY6OtEdZ7CDhelxvONSHI41OKGo9Q/edit

**Comment by jpstroop** [comment]
It seems like associating them somehow makes sense. Maybe document on the wiki and then we embed the ERD on the same page?

**Comment by jpstroop** [comment]
`<img src="https://docs.google.com/drawings/d/1MLnL8JpUS84DX7fY6OtEdZ7CDhelxvONSHI41OKGo9Q/pub?w=960&amp;h=720">`

**Comment by escowles** [comment]
I've written up a wiki page laying out the identifiers and our handling of them, embedding the updated simplified ER diagram:

https://github.com/pulibrary/cicognara-rails/wiki/Identifiers
