### ISSUE TITLE
How many roles do we have?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#23]
Determines how we implement roles for creators.

**Comment by tampakis** [comment]
1xx and 7xx $4 and $e

**Comment by jpstroop** [comment]
former owner
author
engraver
printer

**Comment by cwulfman** [comment]
//datafield[@tag='100' or @tag='700']/subfield[@code='e' and not(contains(., 'micro'))]

**Comment by cwulfman** [comment]
``
declare namespace marc="http://www.loc.gov/MARC21/slim";

let $hits := //marc:datafield[starts-with(@tag, '1') or starts-with(@tag, '7')]/marc:subfield[@code='e']
for $hit in distinct-values($hits)
order by $hit
return concat($hit, "&#10;")
``

artist.
 associated name.
 attributed name.
 author.
 bookseller.
 editor.
 engraver.
 etcher.
 former owner
 former owner.
 honouree.
 ill.
 illus.
 printer.
 publisher.
 tr.
