### ISSUE TITLE
MultiVolumeWorks don't work

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#237]
UV can't handle collections within collections within collections.  Maybe we should flatten these into manifests instead of collections?  Are there other options?

**Comment by escowles** [comment]
Maybe we should simply load the first version in the viewer, and not depend on the index tab for loading the other versions in the viewer?  For example, we could have links immediately below the viewer that would reload the viewer with the other manifests?

**Comment by tpendragon** [comment]
Another option would be to fix ranges in Plum and use Mirador.

**Comment by escowles** [comment]
There are other reasons to use Mirador, so that seems like a good option, as long as fixing ranges in Plum isn't too hard.

**Comment by escowles** [comment]
Related to #238
