### ISSUE TITLE
Create TEI indexing rake task

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#24]
xml:id --> id
    ciconum --> cico_s (the @n)
    dclib --> dclib_s (the @corresp)
    textblob --> description_t (the body of the tei:item)

Output: An array of hashes:
[ { "id": ., "dclib": [], }, { ... }]

Then,
Write a rake task that takes the output of the above and pulls it into SOLR.

**Comment by cwulfman** [comment]
Write method in catalogo repo to generate a json hash of records:

1. xml:id --> id
2. ciconum --> cico_s (the @n)
3. dclib --> dclib_s (the @corresp)
4. textblob --> description_t  (the body of the tei:item)


Output: An array of hashes:
[ { "id": ., "dclib": [], }, { ... }]

Then,
Write a rake task that takes the output of the above and pulls it into SOLR.

**Comment by escowles** [comment]
@cwulfman I'm trying to understand the division of labor between the various indexing parts.

Based on our discussion this morning, I thought we would have a single task that parsed the TEI, matched it with the MARC data, and updated Solr.  The MARC data could either be read from files on disk, or from Solr.  Reading it from Solr would have the benefit of having a single place to make changes to the MARC data and not have to duplicate those in the TEI indexer.

Given the need for a significant amount of logic in the rake task (as opposed to just splitting JSON and shoving it into Solr), I'm not sure transforming the TEI to the JSON helps enough to justify having to maintain another tool.  Is there a reason why we can't just have the rake task work off the TEI file directly?  I'd be happy to work with you on getting the Nokogiri part setup, or you can crib from the [METS parsing in Plum](https://github.com/pulibrary/plum/blob/master/app/models/mets_document.rb).

**Comment by cwulfman** [comment]
@tampakis and I were talking about this this afternoon: we considered that the TEI transcriptions are external to the app and didn't want to build a dependency, so thought the Ruby code for generating documents to push into Solr should live with the transcriptions. I can certainly see the advantage of encapsulating the XML parsing and Solr updating in a single place, though.

How should we configure a path to the TEI xml?

**Comment by escowles** [comment]
The rake task could take the TEI filename as an argument.  Then you'd need to checkout the cicognara-catalogo repo and point to it.  We could even make that a submodule if we wanted to make the connection explicit.

**Comment by cwulfman** [comment]
Sounds reasonable.

**Comment by cwulfman** [comment]
Need fixtures for the rake task.
