### ISSUE TITLE
Harvest partner records/manifests from Getty Research Portal

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#267]
This will result in a viewer for everything that Getty has a IIIF manifest for.
Make sure to pull in info for #29

**Comment by escowles** [comment]
Sample record dump from Getty:
[resourcedump_Cicognara-part1.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5543ba34bce77277007af7ff/125516c66e82c728ace21e0d46fa91892c9791aa8aedaa4eb462d39d2a49207d2816a2666084f13cee0037431f1d11f6140b1b56f6eb8c2ca7e03470dc555deed53e5e70953f11acead41ab752b232975dc7e7e2de139db17770a599855d3f190f198cfb5937a1904fca5ff74be75f18.zip)

**Comment by escowles** [comment]
The ResourceSync dumps are now live on the Getty Research Portal:

Download the JSON-LD version of the data:
http://portal.getty.edu/resources/json_data/resourcedump.xml
 
Download the XML version of the data:
http://portal.getty.edu/resources/xml_data/resourcedump.xml

**Comment by hackmastera** [comment]
resourcesync: http://www.openarchives.org/rs/toc

**Comment by tpendragon** [comment]
So reading the spec and the output of the XML, it looks like each date is a full `resourcedump` of Getty. http://portal.getty.edu/resources/xml_data/resourcedump.xml says they don't support change dumps.

**Comment by tpendragon** [comment]
I have this working now (305 manifests with valid DCL numbers from Heidelberg), but #339 needs to be finished before this is viable.
