### ISSUE TITLE
Reindex with deploy?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/cicognara-rails#317]
Reindexing was separated from deployment in #315. However, this seems like a useful process. A user will have to manually reindex after every deployment. Should we revert to the original behavior?

**Comment by escowles** [comment]
The Solr index survives deployment, but the generated HTML pages in `/app/views/pages/catalogo` don't.  Maybe those should be moved to `shared` or not stored on the filesystem at all (e.g., stored in db or generated on the fly)?

**Comment by escowles** [comment]
Related to https://github.com/pulibrary/cicognara-rails/issues/236
