### ISSUE TITLE
Get Princeton data into Getty Research Portal

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#330]
This will result in a viewer for everything we've ingested the Microfiche for, after pulibrary/cicognara-rails#267

**Comment by escowles** [comment]
Talk to Adam Brin at Getty

**Comment by hackmastera** [comment]
We're the ones importing these records again, right? So the manifest url should be in an 85641|u. That's also where the ark link is.  Is it okay if there are other 856es? or should I scrub them and re-add the ones we need?

**Comment by escowles** [comment]
In theory, other people could be importing these MARC records to add the electronic resources to their local catalogs, but in practice I think it's probably only us. So if it's easier to scrub the other 856s, that's fine.

**Comment by hackmastera** [comment]
Here's an MD description from Adam about what their parser looks at; he said most of it should be standard.

https://gist.github.com/hackmastera/30a90369c8c061dd4eb3106687c68ee2

**Comment by escowles** [comment]
This is mostly working, but around 600 records are not linked to the Cicognara virtual collection correctly because of https://github.com/pulibrary/figgy/issues/2845
