### ISSUE TITLE
Display digital object metadata

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#334]
When displaying the viewer, also display the source record metadata.  The goal here is to display the standardized Getty Research Portal metadata that may contain copy-specific information and notes, which may not be included in the IIIF manifest.

The fields that show up should be the same as those which show up below it.

We'll get the MARC records from the Getty API probably. Needs some research.

The MARC record we have now should only show up when the Microfiche is selected.

We'll have to attach metadata to a Version in order to do this. An easy way might be to serialize a hash into a new field on the Version.

**Comment by escowles** [comment]
Simple wireframe: https://docs.google.com/drawings/d/11eCEYqNjT7JbkG5UajUfC-_riVIGDSAaejCYPKgIvZ4/edit

**Comment by tpendragon** [comment]
@escowles They want the metadata to change when the tabbed viewer changes?

**Comment by escowles** [comment]
@tpendragon Yes — I'll try to make that clear in the wireframe.

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/cicognara-rails/issues/267

**Comment by hackmastera** [comment]
Questions:

1. Can we use the json we get from the getty resourcesync endpoint? Otherwise, if we're following see also from manifests we're not necessarily getting MARC. In the case used as a fixture for https://github.com/pulibrary/cicognara-rails/pull/354 it's pointing to a MODS/METS record.

**Comment by hackmastera** [comment]
Fields we want to store / display:
https://github.com/pulibrary/cicognara-rails/blob/3d648ffd5142bf246ab6f63d33b9c384a5943d42/app/controllers/catalog_controller.rb#L109-L131

**Comment by escowles** [comment]
I've reviewed the notes from recent project calls, and there are definitely places where they assume the metadata from the Getty Research Portal is what we'll display. And looking at the seeAlso values, I do see some METS and other things there, not just MARC.

> Answer: no, doesn't look like this gives us the author, publisher, date type metadata

The items I looked at from the most recent dump (http://portal.getty.edu/resources/json_data/resourcedump_2019-10-14-part1.zip) had author/title/date/etc. info.

**Comment by hackmastera** [comment]
> I've reviewed the notes from recent project calls, and there are definitely places where they assume the metadata from the Getty Research Portal is what we'll display.

Awesome. Let's do that then. I guess the records will be somewhat variable. But presumably they can always enhance what they're sending to Getty.

**Comment by hackmastera** [comment]
@escowles According to your wireframe and the work we've done so far, the "book" metadata, i.e. the current contents of that box, will no longer be displayed. Only metadata for each individual Version will be displayed. Is that what you / stakeholders expect? Thanks!

**Comment by escowles** [comment]
Yes, I think that's fine — the metadata displayed for the microfiche should be the same as what's displayed now.

**Comment by lightgivener** [comment]
Hey! 
Sorry need some clarification on this:

NGA MARC metadata will only display when Fiche in selected in viewer?

Then what bibliographical records will display for digital surrogates?

Have no recollection of this being discussed in project call, an example would be helpful to understand.

Thanks!

(And hello to the ones i do not as of yet know!)

**Comment by escowles** [comment]
@lightgivener My understanding is that what we talked about is:
* When you first load the page, the microfiche should display with the NGA MARC metadata
* When you switch to a different digital object, it should display the metadata associated with that digital object (replacing the NGA MARC metadata)
* If there is no microfiche or other digital objects, then we can display the NGA MARC metadata as a fallback

Is that not how you remember it?

**Comment by lightgivener** [comment]
Hey! I thought the outside surrogate manifests would not even come with their MARC sets, but only the Manifest would be submitted. And then basic copy info would be accessable in the Viewer info section of the right?

Your version does make sense but no this is actually not what I remeber. I don't have much time now but lets check in on this again soonish!

thanks!

**Comment by hackmastera** [comment]
Hi @lightgivener, nice to meet you! I can't really add to the use case portion of this discussion.

But @cwulfman and I want to leave some implementation notes on next steps for ourselves for next week:
We've got a new `imported_metadata` field on the Version model. Next step is to populate it during the getty ingest scripts which were added in https://github.com/pulibrary/cicognara-rails/pull/354. In particular, we expect to add a test around https://github.com/pulibrary/cicognara-rails/pull/354/files#diff-8de88da2a1e2b66150c9d386ef5fc2daR31 that we're indexing a hash into `imported_metadata` with keys pulled from https://github.com/pulibrary/cicognara-rails/blob/3d648ffd5142bf246ab6f63d33b9c384a5943d42/app/controllers/catalog_controller.rb#L109-L131.

Tooling is set up to then present those hashes as solr documents in metadata divs on the show page.

Final step will be to hide / show those divs in response to click events on the tabs which currently control the viewer display.

We'll also need to explicitly test that the third case, where there are no versions but we want to still display the metadata, remains true.

**Comment by hackmastera** [comment]
There's definitely some variability in these json records, even among the 3 we have in the fixtures file. E.g. in some the subjects have types, but in one they only have labels. But I think I have covered all the known fields. The list of fields Adam sent me is below; it is close to one of the contexts in one of the fixtures, but it doesn't precisely match any of them, and none of them precisely match one another.

```
    "@context": {
        "source": "http://purl.org/dc/elements/1.1/source",
        "Person": "http://schema.org/Person",
        "creator": "http://purl.org/dc/elements/1.1/creator",
        "issued": "http://purl.org/dc/terms/issued",
        "description": "http://purl.org/dc/elements/1.1/description",
        "extent": "http://purl.org/dc/terms/extent",
        "format": "http://purl.org/dc/elements/1.1/format",
        "identifier": "http://purl.org/dc/elements/1.1/identifier",
        "URI": "http://purl.org/dc/terms/URI",
        "oclc": "http://portal.getty.edu/terms/gri/oclc",
        "language": "http://purl.org/dc/elements/1.1/language",
        "title": "http://purl.org/dc/elements/1.1/title",
        "DCMIType": "http://purl.org/dc/terms/DCMIType",
        "type": "http://purl.org/dc/elements/1.1/type",
        "publisher": "http://purl.org/dc/elements/1.1/publisher",
        "grpContributor": "http://portal.getty.edu/terms/gri/grpContributor"
    },

```
The list of configured index fields we aren't mapping to, because these fields don't appear to come through with the json, is:
```
          # 'tei_author_txt', label: 'Author(s)'  # mapping to author_display instead
          # 'tei_pub_txt', label: 'Publication place(s)' # in fixture data the place is part of publisher
          # 'tei_section_head_italian', label: 'Section head'
          # 'tei_note_italian', label: 'Note(s)'
          # 'title_addl_display', label: 'Other title(s)', helper_method: :ul
          # 'edition_display', label: 'Edition'
          # 'contents_display', label: 'Contents'
          # 'note_display', label: 'Note(s)', helper_method: :html_safe
          # 'title_added_entry_display', label: 'Added entry title(s)'
          # 'place_display', label: 'Place of publications'
```

**Comment by hackmastera** [comment]
Okay I went through all the json files and created a combined context hash. Here it is:
```
{"source"=>"http://purl.org/dc/elements/1.1/source",
 "Person"=>"http://schema.org/Person",
 "creator"=>"http://purl.org/dc/elements/1.1/creator",
 "contributor"=>"http://purl.org/dc/elements/1.1/contributor",
 "spatial"=>"http://purl.org/dc/terms/spatial",
 "coverage"=>"http://purl.org/dc/elements/1.1/coverage",
 "issued"=>"http://purl.org/dc/terms/issued",
 "description"=>"http://purl.org/dc/elements/1.1/description",
 "extent"=>"http://purl.org/dc/terms/extent",
 "format"=>"http://purl.org/dc/elements/1.1/format",
 "identifier"=>"http://purl.org/dc/elements/1.1/identifier",
 "URI"=>"http://purl.org/dc/terms/URI",
 "oclc"=>"http://portal.getty.edu/terms/gri/oclc",
 "language"=>"http://purl.org/dc/elements/1.1/language",
 "isReferencedBy"=>"http://purl.org/dc/terms/isReferencedBy",
 "relation"=>"http://purl.org/dc/elements/1.1/relation",
 "LCSH"=>"http://purl.org/dc/terms/LCSH",
 "LCC"=>"http://purl.org/dc/terms/LCC",
 "subject"=>"http://purl.org/dc/elements/1.1/subject",
 "alternative"=>"http://purl.org/dc/terms/alternative",
 "title"=>"http://purl.org/dc/elements/1.1/title",
 "DCMIType"=>"http://purl.org/dc/terms/DCMIType",
 "aat"=>"http://www.getty.edu/research/tools/vocabularies/aat/",
 "type"=>"http://purl.org/dc/elements/1.1/type",
 "publisher"=>"http://purl.org/dc/elements/1.1/publisher",
 "grpContributor"=>"http://portal.getty.edu/terms/gri/grpContributor",
 "date"=>"http://purl.org/dc/elements/1.1/date",
 "iiif"=>"http://portal.getty.edu/terms/cicognara/iiif",
 "hasFormat"=>"http://purl.org/dc/terms/hasFormat",
 "rights"=>"http://purl.org/dc/elements/1.1/rights",
 "Organization"=>"http://schema.org/Organization",
 "temporal"=>"http://purl.org/dc/terms/temporal",
 "requires"=>"http://purl.org/dc/terms/requires",
 "accessRights"=>"http://purl.org/dc/terms/accessRights",
 "dateCopyrighted"=>"http://purl.org/dc/terms/dateCopyrighted",
 "gnd"=>"https://d-nb.info/standards/elementset/gnd",
 "series"=>"http://portal.getty.edu/terms/gri/series",
 "isPartOf"=>"http://purl.org/dc/terms/isPartOf",
 "gndSubject"=>"https://d-nb.info/standards/elementset/gnd#subjectHeading",
 "edition"=>"http://portal.getty.edu/terms/gri/edition",
 "cicognaraNumber"=>"http://portal.getty.edu/terms/cicognara/cicognaraNumber",
 "dclNumber"=>"http://portal.getty.edu/terms/cicognara/dclNumber",
 "virtualCollection"=>"http://portal.getty.edu/terms/gri/virtualCollection",
 "isVersionOf"=>"http://purl.org/dc/terms/isVersionOf",
 "hasVersion"=>"http://purl.org/dc/terms/hasVersion",
 "isReplacedBy"=>"http://purl.org/dc/terms/isReplacedBy",
 "tableOfContents"=>"http://purl.org/dc/terms/tableOfContents",
 "provenance"=>"http://purl.org/dc/elements/1.1/provenance",
 "NLM"=>"http://purl.org/dc/terms/NLM",
 "created"=>"http://purl.org/dc/terms/created",
 "abstract"=>"http://purl.org/dc/terms/abstract",
 "DDC"=>"http://purl.org/dc/terms/DDC",
 "accrualPeriodicity"=>"http://purl.org/dc/elements/1.1/accrualPeriodicity",
 "hasPart"=>"http://purl.org/dc/terms/hasPart",
 "replaces"=>"http://purl.org/dc/terms/replaces",
 "accrualMethod"=>"http://purl.org/dc/elements/1.1/accrualMethod",
 "aatSubject"=>
  "http://www.getty.edu/research/tools/vocabularies/aat/#subjectHeading",
 "medium"=>"http://purl.org/dc/terms/medium",
 "LCNAF"=>"http://portal.getty.edu/terms/gri/LCNAF",
 "UDC"=>"http://purl.org/dc/terms/UDC",
 "isFormatOf"=>"http://purl.org/dc/terms/isFormatOf"}
count: 61
```

**Comment by hackmastera** [comment]
Nothing comes through the json as a note per se. Perhaps "abstract" from the json should be mapped to "description" in the display, and "description" in the json should be mapped to "notes"?

**Comment by hackmastera** [comment]
@escowles regarding the toggle functionality you outlined:

> My understanding is that what we talked about is:

> When you first load the page, the microfiche should display with the NGA MARC metadata
> When you switch to a different digital object, it should display the metadata associated with that digital object (replacing the NGA MARC metadata)
> If there is no microfiche or other digital objects, then we can display the NGA MARC metadata as a fallback
 
When you first load the page there is a digital object selected with that viewer displayed. Shouldn't we start out displaying the metadata associated with that digital object? I.e. the MARC metadata will only display in the 3rd case you reference, when there are no digital objects.

**Comment by escowles** [comment]
@hackmastera I think the metadata associated with the microfiche is the MARC metadata from NGA. So I think we should show the microfiche objects by default, with the associated metadata from NGA (and having that be filtered through the Getty is fine, to make that process more consistent across different digital objects).

**Comment by hackmastera** [comment]
Okay, currently the microfiche isn't the one shown by default, so we'll have to do that.

**Comment by escowles** [comment]
👍 I thought we had an issue for that, but I don't see one.  So I created https://github.com/pulibrary/cicognara-rails/issues/423 for displaying the microfiche first.
