### ISSUE TITLE
Logging into Staging/Prod is broken

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/cicognara-rails#348]
Get a missing client_id error.

**Comment by jrgriffiniii** [comment]
The GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET were not preserved in the Cicognara Ansible Playbooks.

**Comment by jrgriffiniii** [comment]
This has been updated using https://github.com/pulibrary/princeton_ansible/compare/cicognara-rails-issues-348-google?expand=1, but the callback for the staging environment URL still needs to be updated:
```
Error: redirect_uri_mismatch

The redirect URI in the request, https://cicognara-staging.princeton.edu/users/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/....apps.googleusercontent.com?project=...


```

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/cicognara-rails/issues/348#issuecomment-469374660 is related to https://github.com/pulibrary/cicognara-rails/issues/350, as I'm not able to reproduce this in the production environment.  I believe that the OAuth configuration needs to have the callback URI updated to permit authentication from both the staging and production environments.

**Comment by escowles** [comment]
@jrgriffiniii Sorry — I updated it, but neglected to remove the `/cicognara/` path that was present in lib-rubydev.princeton.edu. I've fixed the URL and I can login in staging now.

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/princeton_ansible/pull/458

**Comment by escowles** [comment]
pulibrary/princeton_ansible#458 was used to update the configuration in staging and production to resolve this issue.
