### ISSUE TITLE
Squirrel away copies of the Memofonte PDFs?

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-rails#361]
See http://www.memofonte.it/ricerche/biblioteche-darte/#leopoldo-cicognara

**Comment by escowles** [comment]
I don't see a copyright statement in http://www.memofonte.it/home/files/pdf/CATALOGO_CICOGNARA.pdf — neither "All Rights Reserved" nor anything about CC/public domain/etc. Do we know what license/rights it has?

**Comment by cwulfman** [comment]
I don't know what rights it has, but I seem to remember we wrote them and got their approval.  I can see if I can track that correspondence down.
