### ISSUE TITLE
Appendix not showing up in Browse Catalogo menu

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#384]
It works at https://cicognara.org/catalogo/section_2.19, but is not shown in the left-hand menu.

**Comment by lightgivener** [comment]
btw the Appendix is NOT what i reffered to what Heidelberg has as Addendum.

See Heidelberg order here (you have to open subject to see the chapters which isn't ideal)

https://digi.ub.uni-heidelberg.de/en/sammlungen/cicognara.html

best!

**Comment by kelynch** [comment]
This appears to have been resolved with one of the recent commits that regenerated the section partials - https://cicognara-staging.princeton.edu/catalogo
