### ISSUE TITLE
Getty Import should have a transaction per imported resource, not as a whole

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/cicognara-rails#394]
We should be able to see the changes as it goes, and if it crashes in the middle we shouldn't have to do everything from the beginning.

Happens here: https://github.com/pulibrary/cicognara-rails/blob/95903c6e8e23851cf563d7668552c7bbf52db024/app/services/getty_parser/importer.rb#L9

**Comment by hackmastera** [comment]
It seems like more than just moving the transaction would be required to restart at a given point after a failure. Maybe that should be a different ticket if it's something we want.
