### ISSUE TITLE
Update README to give instructions for logging in by creating a User

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-rails#400]
In development, following the link at the bottom of the index page (http://localhost:3000/users/auth/google_oauth2) generates a 400 error: "error invalid_request Missing required parameter client_id"

**Comment by hackmastera** [comment]
Apparently the google oauth business requires a key. It didn't sound like we were really interested in messing with that for development purposes.

A workaround is to create a User in the rails console. `application_controller` then auto-logs you in during development. We should update the README to say this -- making this a documentation ticket.
