### ISSUE TITLE
UV not displaying in iframe in Opera

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/cicognara-rails#407]
On [production](https://cicognara.org/catalog/7), the square just spins; in [local dev](http://localhost:3000/catalog/7) nothing shows at all.  Related to removal of pul_uv_rails?

```html
<iframe id="uv-frame" allowfullscreen="true" src="https://figgy.princeton.edu/uv/uv#?manifest=https%3A%2F%2Ffiggy.princeton.edu%2Fconcern%2Fscanned_resources%2Fb5681e67-00fd-43e5-a87c-1c39e8f57608%2Fmanifest"></iframe>
```

**Comment by tpendragon** [comment]
Not related to the pul_uv_rails change, since that's not deployed yet.

**Comment by tpendragon** [comment]
@cwulfman It's loading in Opera for me on a Mac in production.

**Comment by cwulfman** [comment]
It's an extension problem: Privacy Badger Version 2019.10.28 in Opera Version:64.0.3417.92.  Disabling Privacy Badger allows proper behavior, as does adding cicognara.org to Privacy Badger's list of disabled sites. I've sent a report to Privacy Badger.
