### ISSUE TITLE
Add descriptive fields to the ERD

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#41]

**Comment by escowles** [comment]
I've updated the ER diagram to have all the fields from the Rails models:

https://docs.google.com/drawings/d/1MLnL8JpUS84DX7fY6OtEdZ7CDhelxvONSHI41OKGo9Q/edit

This doesn't include anything from the MARC records though.

**Comment by jpstroop** [comment]
Added the fields we'll want to derive from MARC to the Book

**Comment by jpstroop** [comment]
Actually...I'm confused now about what goes w/ Book and what goes w/ version, so what I added might be wrong

**Comment by escowles** [comment]
I *think* that those fields go in Book (there are similar fields in Version e.g., both have edition statements, etc.)

**Comment by jpstroop** [comment]
Yeah, I think so too, just questioning how we'd ever add another Book, assuming the set of MARC records is closed.

**Comment by jpstroop** [comment]
:ok: to close?

**Comment by escowles** [comment]
Yep, I think this is good.
