### ISSUE TITLE
show toggle for metadata display boxes isn't working

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/cicognara-rails#436]
Presumably bug is around here https://github.com/pulibrary/cicognara-rails/blob/b42c83666204cbfc535a9938ad19696e3579fe8a/app/assets/javascripts/application.js#L35

**Comment by cwulfman** [comment]
Could you provide an example of this bug, please?

**Comment by escowles** [comment]
I've been able to trigger this bug on any page with multiple viewers, e.g., https://cicognara.org/catalog/2475

* When I first load the page, the first viewer is displayed with metadata underneath. 
* When I select another viewer, the metadata box disappears (screenshot below)
* Going back to the original viewer doesn't restore the metadata box.

![Screen Shot 2019-12-13 at 3 35 27 PM](https://user-images.githubusercontent.com/856924/70830554-6ee95a80-1dbe-11ea-9f39-4e747ce13059.png)
