### ISSUE TITLE
Wireframe options for displaying scanned Catalgo

### ISSUE THREAD

**Issue by escowles** [pulibrary/cicognara-rails#442]
Blocks #382 

We would like some options for displaying the link to the Vatican copy of the annotated catalogo.

It should be shown on the "Browse Full Catalogo" page (https://cicognara.org/catalogo), and should probably be displayed on the search results pages.

Likely link/button text "Vatican Annotated Catalogo".

**Comment by tpendragon** [comment]
Possible options discussed:

1. A link on the front page.
2. A link at the top of the table contents in https://cicognara.org/catalogo
3. Some text at the top of https://cicognara.org/catalogo that says something like "You might be interested in the Vatican's Annotated Catalogo Copy: link"

**Comment by escowles** [comment]
Maybe related: there are a couple of other versions of the catalogo we could link to:
* PDF volumes in github (these could be loaded into Figgy): https://github.com/pulibrary/cicognara-catalogo/tree/master/memofonte_edition
* Our TEI derived from those PDFs: https://github.com/pulibrary/cicognara-catalogo/blob/master/catalogo.tei.xml

**Comment by lightgivener** [comment]
Heidelberg also has a scan online, which I think also has OCR

**Comment by kelynch** [comment]
## Wireframe options attached:
### Homepage option: 
<img width="1213" alt="Screen Shot 2022-01-11 at 3 55 00 PM" src="https://user-images.githubusercontent.com/7795797/149020151-a7aa2062-ef0a-40a5-ad08-9a4540937402.png">

### Table of contents option: 
<img width="1296" alt="Screen Shot 2022-01-11 at 3 49 19 PM" src="https://user-images.githubusercontent.com/7795797/149020229-1b4931d3-1c2a-4e85-b662-1c28001b2560.png">

### Catalogo browse link (top right) option
<img width="1213" alt="Screen Shot 2022-01-11 at 3 52 41 PM" src="https://user-images.githubusercontent.com/7795797/149020292-160749eb-cdeb-49de-8d4c-de4b5046c62e.png">

**Comment by kelynch** [comment]
@escowles We have some wireframes for this feature ready for review, feedback welcome!

**Comment by escowles** [comment]
@kelynch For the search results, I think I like the Table of Contents option better than having the link on the right under the heading.

For the home page, I wonder if we can should move the "Browse full Catalogo" button under the search box, and put the "Vatican Annotated Catalogo" as a second button next to it?
