### ISSUE TITLE
Subject/Name facet searches don't work.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/cicognara-rails#443]
See links here: https://cicognara.org/catalog/2475

**Comment by kelynch** [comment]
It appears that this may actually be working, just slow to render?

**Comment by escowles** [comment]
When I click on any of the Subject links e.g.,  "Delle Antichità in genere" (https://cicognara.org/catalog?f%5Bsubject_facet%5D%5B%5D=Delle+Antichit%C3%A0+in+genere), I get no hits in the search results.
