### ISSUE TITLE
Version deployment to production

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/cicognara-rails#524]
- [x] Tag a release of the current version
- [x] Ensure this release is on both cicognara servers

Review version/branch deployed to production.

It looks like we deployed `main` to production on 3/11/2022, which is good news, at one point it looked like we had deployed a branch:

```
$ hostname
cicognara1

$ cat revisions.log 
[...]
Branch v1.0.1 (at f0ad9d381ddc9f4375af43568a8ec2c618a3b0ce) deployed as release 20211011174336 by deploy
Branch v1.0.2 (at 8de789f63bbc9e6d39313011f67a1506f521e44f) deployed as release 20211014135812 by deploy
Branch main (at 409b8176d92f5acf426ce1ff64606b71a21c37a1) deployed as release 20211123155603 by deploy
Branch main (at 5c346f597ccd26264e2adfa058fe290636e8b51c) deployed as release 20220311161202 by deploy
```

We probably want to create a release for our next deployment (e.g. `v1.0.3`) but we are OK for now.

**Comment by bess** [comment]
v1.0.4 is now tagged and deployed to both staging and production.
