### ISSUE TITLE
Contributing Institution facet bug

### ISSUE THREAD

**Issue by kelynch** [pulibrary/cicognara-rails#534]
Reported by user over email:

"...I cannot narrow to "contributing library" in the advanced search. Is this a current or ongoing issue? Is there a better way to glean information about contributors via the website? The Masterfile is not so easy to navigate and we need a way to confirm and narrow by contributor."

Actual faceted narrowing appears to be functioning in basic and advanced search.  Follow-up to previous communication:

"...my concern is that it is only showing 9 items... and only from The Frick, Heidelberg, and BAV...[previously] one could narrow the "browse full catalogo" to the contributing partner with this feature. I do not see Princeton, The Getty, or the Met in these choices..."

**Comment by lightgivener** [comment]
Happy to help with navigating the Masterfile. I remember there was an idea to transfer the information into another database as well? Feel free to reach out if there are any questions. Cheers, Charlotte

**Comment by kelynch** [comment]
Thank you!  I think that this is resolved with re-running a Solr indexing task; it appears to be resolved, just waiting for confirmation from the reporting user!  I'll follow up here if more is needed.
