### ISSUE TITLE
Troubleshooting Harvard count from resource portal dump

### ISSUE THREAD

**Issue by kelynch** [pulibrary/cicognara-rails#544]
Harvard item count is at 67 in the site but there are 83 items in the resource dump.  Troubleshoot to determine what is missing.

**Comment by hectorcorrea** [comment]
We found that the Getty data dump includes indeed 83 files for Harvard, all of them are found on `resourcedump_2022-10-31-part3.zip` (download from here http://portal.getty.edu/resources/json_data/resourcedump.xml)

During processing 18 of them are failing to import with message "no matching Book entry for DCL xxx".

```
Unable to import http://portal.getty.edu/books/hul_990016390930203941 - no matching Book entry for DCL dcl:8w6/vol01
Unable to import http://portal.getty.edu/books/hul_990054802000203941 - no matching Book entry for DCL dcl:nw6
Unable to import http://portal.getty.edu/books/hul_990085529710203941 - no matching Book entry for DCL dcl:jcv
Unable to import http://portal.getty.edu/books/hul_990023458840203941 - no matching Book entry for DCL dcl:0m3
Unable to import http://portal.getty.edu/books/hul_990056313670203941 - no matching Book entry for DCL dcl:6st
Unable to import http://portal.getty.edu/books/hul_990065165000203941 - no matching Book entry for DCL dcl:9ks
Unable to import http://portal.getty.edu/books/hul_990096206550203941 - no matching Book entry for DCL dcl:jwk
Unable to import http://portal.getty.edu/books/hul_990052901710203941 - no matching Book entry for DCL dcl:p0k
Unable to import http://portal.getty.edu/books/hul_990049089240203941 - no matching Book entry for DCL dcl:vs9
Unable to import http://portal.getty.edu/books/hul_990054838920203941 - no matching Book entry for DCL dcl:ckv
Unable to import http://portal.getty.edu/books/hul_990021547270203941 - no matching Book entry for DCL dcl:p35
Unable to import http://portal.getty.edu/books/hul_990034493580203941 - no matching Book entry for DCL dcl:6cq/vol01
Unable to import http://portal.getty.edu/books/hul_990056860020203941 - no matching Book entry for DCL dcl:cd4
Unable to import http://portal.getty.edu/books/hul_990018263160203941 - no matching Book entry for DCL dcl:c6c
Unable to import http://portal.getty.edu/books/hul_990000060160203941 - no matching Book entry for DCL dcl:111
Unable to import http://portal.getty.edu/books/hul_990061254250203941 - no matching Book entry for DCL dcl:4x6
Unable to import http://portal.getty.edu/books/hul_990028582360203941 - no matching Book entry for DCL dcl:m8v
Unable to import http://portal.getty.edu/books/hul_990003403540203941 - no matching Book entry for DCL dcl:scb/vol01
```

It seems that these records are not found on the source `catalogo.tei.xml` coming from https://github.com/pulibrary/cicognara-catalogo/

**Comment by hectorcorrea** [comment]
The root of the problem seems to be that the records are failed to be imported because there is no match for them in the `Books` table. 

To the best of my knowledge the `Books` table is populated with data from the `public/cicognara.mrx.xml` (or is it `public/cicognara.marc.xml`?) and there is indeed to match for the missing records in this MARC XML file. This is the code that process the MARC XML: https://github.com/pulibrary/cicognara-rails/blob/main/lib/cicognara/tei_indexer.rb#L88

**Comment by hectorcorrea** [comment]
Here is a snippet of the `public/cicognara.mrx.xm` that shows how the DCL number and CICO are recorded for MARC records under field `024`:

```
...
  <record>
    <leader>01296cam a2200289Mi 4500</leader>
    <controlfield tag="001">10084756</controlfield>
    <controlfield tag="005">20170116133726.0</controlfield>
    <controlfield tag="007">hu uuu---uuuu</controlfield>
    <controlfield tag="008">000202s1708    xx      b     000 0 ger d</controlfield>
    <datafield ind1=" " ind2=" " tag="035">
      <subfield code="a">(OCoLC)ocn313540341</subfield>
    </datafield>
    <datafield ind1="7" ind2=" " tag="024">
      <subfield code="a">465</subfield>
      <subfield code="2">cico</subfield>
    </datafield>
    <datafield ind1="7" ind2=" " tag="024">
      <subfield code="a">dcl:zc5</subfield>
      <subfield code="2">dclib</subfield>
    </datafield>
...
```

**Comment by hectorcorrea** [comment]
Sort of good news. I hard-coded a fake MARC record in `cicognara.mrx.xml` with the proper subfields to represent one of the missing records (`dcl:nw6`) 
```
    <datafield ind1="7" ind2=" " tag="024">
      <subfield code="a">365</subfield>
      <subfield code="2">cico</subfield>
    </datafield>
    <datafield ind1="7" ind2=" " tag="024">
      <subfield code="a">dcl:nw6</subfield>
      <subfield code="2">dclib</subfield>
    </datafield>
```
re-ran the import and the record was imported (see screenshot below):

![cicognara_nw6](https://user-images.githubusercontent.com/568286/204646288-a3089628-924d-464a-aec8-a5273093bdad.png)

Surprisingly some of the data shows correctly, like the author, date, and title *even though* my fake hard coded MARC record had other values. It's possible it picking these values from the `catalogo.tei.xml` since I added the attribute `corresp="dcl:nw6"` to the record on that file.

**Comment by hectorcorrea** [comment]
With the MARC and TEI files updated (https://github.com/pulibrary/cicognara-catalogo/pull/165) I was able to re-run the import in production and get the correct number of records for Harvard (83) to [show in production](https://cicognara.org/catalog?f%5Bcontributing_library_facet%5D%5B%5D=Harvard+Library&q=&search_field=all_fields).

```
cd /opt/cicognara/current
TEIPATH=public/cicognara.tei.xml MARCPATH=public/cicognara.mrx.xml bundle exec rake tei:catalogo:update
TEIPATH=public/cicognara.tei.xml MARCPATH=public/cicognara.mrx.xml bundle exec rake tei:index
TEIPATH=public/cicognara.tei.xml MARCPATH=public/cicognara.mrx.xml bundle exec rake tei:partials
TEIPATH=public/cicognara.tei.xml MARCPATH=public/cicognara.mrx.xml bundle exec rake getty:import
TEIPATH=public/cicognara.tei.xml MARCPATH=public/cicognara.mrx.xml bundle exec rake tei:index
```

Notice that although no code changes were required on this repo to correct the data, I did create a separate PR (https://github.com/pulibrary/cicognara-rails/pull/545) that adds a couple of rake tasks to help re-generate the MARC XML and TEI XML snippets applied to the [cicognara-catalogo files](https://github.com/pulibrary/cicognara-catalogo/pull/165) in case we need to do this again in the future (and it also serves as documentation.)
