### ISSUE TITLE
Consider high voltage for TEI-based  representation of the catalogo

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/cicognara-rails#72]
See https://github.com/thoughtbot/high_voltage

If each page had a known ID, could use XSLT (2.0 probably, but could shell out to Saxon in a rake task) to generate a partial per page that be able to link to entries in the Blacklight catalog (and the reverse).

**Comment by cwulfman** [comment]
As you know, the TEI encoding we are producing is structured semantically: each section, and each item within each section, is encoded as a XML element (a tei:div). Page breaks are encoded as [milestones](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-milestone.html). 

I have written an XSLT version of [this XQuery chunker](http://wiki.tei-c.org/index.php/Milestone-chunk.xquery), which can probably be used to generate a set of static pages via a shell-out to Saxon. If we shell out to Saxon, though, couldn't we use the XQuery form? Or is XQuery not something you want to support?

**Comment by jpstroop** [comment]
Oh, whichever. I was just thinking XSLT would be easier.

**Comment by jpstroop** [comment]
Had to jog my memory...I was thinking [xsl:result-document](http://www.xmlplease.com/xmltraining/xslt-by-example/examples/result-document_1.html) might be easier since the rest of the conversion to HTML would likely happen in XSLT.

**Comment by cwulfman** [comment]
Sure. Whatever you like!
